# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/cjm-graph-plugin-sqlite',
                'doc_host': 'https://cj-mills.github.io',
                'git_url': 'https://github.com/cj-mills/cjm-graph-plugin-sqlite',
                'lib_path': 'cjm_graph_plugin_sqlite'},
  'syms': {}}
